--- #YAML:1.0
name:                NexposeSimpleXML-Parser
version:             0.04
abstract:            ~
license:             ~
author:              
    - Joshua D. Abraham < jabra@spl0it.org >
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Object::InsideOut:             0
    Test::Class:                   0
    Test::More:                    0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
